stages:
  #- make_assets
  - prepare_view
  #- embed_reveal
  - docusaurus

build_dir: /build
output_type: last
output_dir: /output

lab_structure:
  - title: Lab 1 - Number Representation
    filename: lab1.md
    content:
      - tasks/conversions.md
      - tasks/rotations.md
      - tasks/odd-even.md
      - tasks/len-xor.md
      - tasks/mirror.md
      - reading/binary-hex.md
      - reading/c-pointers.md
  - title: Lab 2 - Memory Operations. Introduction to GDB
    filename: lab2.md
    content:
      - tasks/iterate.md
      - tasks/delete_first.md
      - tasks/pixels.md
      - tasks/find_max.md
      - tasks/pointers.md
      - tasks/inspect.md
      - reading/memory-operations.md
      - guides/array_vs_pointer.md
      - reading/introduction-to-GDB.md
      - guides/segfault.md
  - title: Lab 4 - Toolchain. GOTO
    filename: lab4.md
    content:
      - tasks/goto-algs.md
      - tasks/old-hits.md
      - reading/c-goto-statements.md
      - guides/goto-warm-up.md
      - reading/reverse-engineering.md
      - guides/compiler-explorer-tutorial.md
      - guides/ghidra-tutorial.md
  - title: Lab 5 - Introduction to Assembly Language
    filename: lab5.md
    content:
      - tasks/conditional-jumps.md
      - tasks/grumpy-jumps.md
      - tasks/sets.md
      - tasks/min.md
      - tasks/fibonacci.md
      - tasks/cf-of.md
      - reading/introduction.md
      - reading/x86-architecture-family.md
      - guides/instructions.md
      - guides/discovering-assembly.md
  - title: Lab 6 - Registers and Memory Addressing
    filename: lab6.md
    content:
      - tasks/div.md
      - tasks/mul.md
      - tasks/sum-squared.md
      - tasks/sum-array.md
      - tasks/vec-count-if.md
      - reading/registers.md
      - guides/multiply-divide.md
      - guides/floating-point-exception.md
      - reading/memory-addressing.md
      - guides/addressing-arrays.md
      - guides/declarations.md
      - guides/loop.md
  - title: Lab 7 - Structures, vectors and strings
    filename: lab7.md
    content:
      - tasks/fibonacci.md
      - tasks/print-structure.md
      - tasks/getters-setters.md
      - tasks/find-substring.md
      - tasks/mul-arrays.md
      - tasks/courses.md
      - reading/structures.md
      - guides/students.md
      - reading/arrays.md
      - guides/max.md
  - title: Lab 11 - Buffer Management. Buffer Overflow
    filename: lab11.md
    content:
      - tasks/data-buffer.md
      - tasks/stack-buffer.md
      - tasks/read-stdin-gets.md
      - tasks/read-stdin-fgets.md
      - tasks/overflow-in-c.md
      - tasks/overwrite-ret-addr.md
      - tasks/overflow-for-binary.md
      - reading/buffers-intro.md
      - reading/overflow-vuln.md
# make_assets:
#   plugin: command
#   options:
#     command: make
#     locations:
#       - chapters/template-chapter/template-topic/slides
#       - chapters/hardware-software-interface
#       - chapters/intro-computer-architecture
#       - chapters/memory-layout
#       - chapters/memory-security
#     args:
#       - all

prepare_view:
  plugin: command
  options:
    command: python
    locations:
      - .
    args:
      - gen-view.py
# embed_reveal:
#   plugin: reveal_embed
#   options:
#     target: docusaurus
#     extension: mdx
#     build:
#       - template-chapter-template-topic: template-chapter-template-topic

#       Hardware-Software-Interface: slides/Hardware-Software-Interface
#       Intro-Computer-Architecture: slides/Intro-Computer-Architecture
#       Memory-Layout: slides/Memory-Layout
#       Memory-Security: slides/Memory-Security

docusaurus:
  plugin: docusaurus
  options:
    course_name: Hardware Software Interface
    math: true
    sidebar: js
    structure:
      - Introduction: /build/prepare_view/.view/landing-page.md
      - Labs:
          path: /build/prepare_view/.view
          extra:
            - media
          subsections:
            - Lab 1 - Number Representation: lab1.md
            - Lab 2 - Memory Operations. Introduction to GDB: lab2.md
            - Lab 4 - Toolchain. GOTO: lab4.md
            - Lab 5 - Introduction to Assembly Language: lab5.md
            - Lab 6 - Registers and Memory Addressing: lab6.md
            - Lab 7 - Structures, vectors and strings: lab7.md
            - Lab 11 - Buffer Management. Buffer Overflow: lab11.md

    # static_assets:
    # - slides/Hardware-Software-Interface: /build/make_assets/chapters/hardware-software-interface
    # - slides/Intro-Computer-Architecture: /build/make_assets/chapters/intro-computer-architecture
    # - slides/Memory-Layout: /build/make_assets/chapters/memory-layout
    # - slides/Memory-Security: /build/make_assets/chapters/memory-security
    config_meta:
      title: Hardware Software Interface
      url: http://localhost/
      baseUrl: /hardware-software-interface/
      onBrokenLinks: warn
      onBrokenMarkdownLinks: warn
    config_socials:
      Main site: https://curs.upb.ro
      OCW: https://ocw.cs.pub.ro/courses/pclp2
      Facebook: https://www.facebook.com/10c1a
    copyright_string: OpenEdu Team
